'safe request' as execution gate

diff --git a/.github/workflows/go_test.yml b/.github/workflows/go_test.yml
--- a/.github/workflows/go_test.yml
+++ b/.github/workflows/go_test.yml
@@ -12,11 +12,16 @@ jobs:
       matrix:
         platform: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{matrix.platform}}
-    if: contains(github.event.pull_request.labels.*.name, 'safe request')
     env:
       DBGSYNCLOG: trace
       DBGSYNCON: true
     steps:
+    - name: Check permission
+      if: contains(github.event.pull_request.labels.*.name, 'safe request') == false
+      run: |
+        echo "::error:: Cannot start testing because safe label is not set'
+        exit 1
+
     - name: Set up Go ^1.19
       uses: actions/setup-go@v3
       with:
